UPSTREAM: time: move the timecounter/cyclecounter code into its own file.
(cherry picked from commit 74d23cc704d19732e70ef1579a669f7d5f09dd9a)

The timecounter code has almost nothing to do with the clocksource
code. Let it live in its own file. This will help isolate the
timecounter users from the clocksource users in the source tree.

Signed-off-by: Richard Cochran <richardcochran@gmail.com>
Acked-by: Jeff Kirsher <jeffrey.t.kirsher@intel.com>
Signed-off-by: David S. Miller <davem@davemloft.net>

This somehow fixes the following error caused by "BACKPORT: partial: mm,
oom_reaper: do not mmput synchronously from the oom reaper context":

  include/linux/mm_types.h:473:21: error: field 'async_put_work' has incomplete type
      struct work_struct async_put_work;

Signed-off-by: joshuous <joshuous@gmail.com>